# Generated by Django 4.2.7 on 2023-12-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_topic_word_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.topic'),
        ),
    ]
