# Generated by Django 4.2.7 on 2023-12-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_word_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translation',
            new_name='TranslatedWord',
        ),
    ]
