# Generated by Django 4.2.7 on 2023-12-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_rename_translation_translatedword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sententse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sentence_eng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.sententse')),
                ('translated_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.translatedword')),
            ],
        ),
    ]
