# Generated by Django 4.2.7 on 2023-12-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_sententse_sentencetranslation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sententse',
            new_name='Sentence',
        ),
    ]
